name: mbta
channels:
  - anaconda
  - defaults
dependencies:
  - attrs=21.4.0
  - brotlipy=0.7.0
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - idna=3.4
  - iniconfig=1.1.1
  - libcxx=14.0.6
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1s
  - packaging=21.3
  - pip=22.2.2
  - pluggy=1.0.0
  - py=1.11.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.9.15
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tk=8.6.12
  - tomli=1.2.2
  - tzdata=2022f
  - urllib3=1.26.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
