import get_route
from unittest.mock import Mock, patch


mock_route_response_json = {'data': [{'attributes': {'color': 'DA291C',
                          'description': 'Rapid Transit',
                          'direction_destinations': ['Ashmont/Braintree',
                                                     'Alewife'],
                          'direction_names': ['South', 'North'],
                          'fare_class': 'Rapid Transit',
                          'long_name': 'Red Line',
                          'short_name': '',
                          'sort_order': 10010,
                          'text_color': 'FFFFFF',
                          'type': 1},
           'id': 'Red',
           'links': {'self': '/routes/Red'},
           'relationships': {'line': {'data': {'id': 'line-Red',
                                               'type': 'line'}}},
           'type': 'route'},
          {'attributes': {'color': 'DA291C',
                          'description': 'Rapid Transit',
                          'direction_destinations': ['Mattapan', 'Ashmont'],
                          'direction_names': ['Outbound', 'Inbound'],
                          'fare_class': 'Rapid Transit',
                          'long_name': 'Mattapan Trolley',
                          'short_name': '',
                          'sort_order': 10011,
                          'text_color': 'FFFFFF',
                          'type': 0},
           'id': 'Mattapan',
           'links': {'self': '/routes/Mattapan'},
           'relationships': {'line': {'data': {'id': 'line-Mattapan',
                                               'type': 'line'}}},
           'type': 'route'},
          {'attributes': {'color': 'ED8B00',
                          'description': 'Rapid Transit',
                          'direction_destinations': ['Forest Hills',
                                                     'Oak Grove'],
                          'direction_names': ['South', 'North'],
                          'fare_class': 'Rapid Transit',
                          'long_name': 'Orange Line',
                          'short_name': '',
                          'sort_order': 10020,
                          'text_color': 'FFFFFF',
                          'type': 1},
           'id': 'Orange',
           'links': {'self': '/routes/Orange'},
           'relationships': {'line': {'data': {'id': 'line-Orange',
                                               'type': 'line'}}},
           'type': 'route'},
          {'attributes': {'color': '00843D',
                          'description': 'Rapid Transit',
                          'direction_destinations': ['Boston College',
                                                     'Government Center'],
                          'direction_names': ['West', 'East'],
                          'fare_class': 'Rapid Transit',
                          'long_name': 'Green Line B',
                          'short_name': 'B',
                          'sort_order': 10032,
                          'text_color': 'FFFFFF',
                          'type': 0},
           'id': 'Green-B',
           'links': {'self': '/routes/Green-B'},
           'relationships': {'line': {'data': {'id': 'line-Green',
                                               'type': 'line'}}},
           'type': 'route'},
          {'attributes': {'color': '00843D',
                          'description': 'Rapid Transit',
                          'direction_destinations': ['Cleveland Circle',
                                                     'Government Center'],
                          'direction_names': ['West', 'East'],
                          'fare_class': 'Rapid Transit',
                          'long_name': 'Green Line C',
                          'short_name': 'C',
                          'sort_order': 10033,
                          'text_color': 'FFFFFF',
                          'type': 0},
           'id': 'Green-C',
           'links': {'self': '/routes/Green-C'},
           'relationships': {'line': {'data': {'id': 'line-Green',
                                               'type': 'line'}}},
           'type': 'route'},
          {'attributes': {'color': '00843D',
                          'description': 'Rapid Transit',
                          'direction_destinations': ['Riverside',
                                                     'Union Square'],
                          'direction_names': ['West', 'East'],
                          'fare_class': 'Rapid Transit',
                          'long_name': 'Green Line D',
                          'short_name': 'D',
                          'sort_order': 10034,
                          'text_color': 'FFFFFF',
                          'type': 0},
           'id': 'Green-D',
           'links': {'self': '/routes/Green-D'},
           'relationships': {'line': {'data': {'id': 'line-Green',
                                               'type': 'line'}}},
           'type': 'route'},
          {'attributes': {'color': '00843D',
                          'description': 'Rapid Transit',
                          'direction_destinations': ['Heath Street',
                                                     'Lechmere'],
                          'direction_names': ['West', 'East'],
                          'fare_class': 'Rapid Transit',
                          'long_name': 'Green Line E',
                          'short_name': 'E',
                          'sort_order': 10035,
                          'text_color': 'FFFFFF',
                          'type': 0},
           'id': 'Green-E',
           'links': {'self': '/routes/Green-E'},
           'relationships': {'line': {'data': {'id': 'line-Green',
                                               'type': 'line'}}},
           'type': 'route'},
          {'attributes': {'color': '003DA5',
                          'description': 'Rapid Transit',
                          'direction_destinations': ['Bowdoin', 'Wonderland'],
                          'direction_names': ['West', 'East'],
                          'fare_class': 'Rapid Transit',
                          'long_name': 'Blue Line',
                          'short_name': '',
                          'sort_order': 10040,
                          'text_color': 'FFFFFF',
                          'type': 1},
           'id': 'Blue',
           'links': {'self': '/routes/Blue'},
           'relationships': {'line': {'data': {'id': 'line-Blue',
                                               'type': 'line'}}},
           'type': 'route'}],
 'jsonapi': {'version': '1.0'}}

mock_subway_data = [{'attributes': {'color': 'DA291C',
                 'description': 'Rapid Transit',
                 'direction_destinations': ['Ashmont/Braintree', 'Alewife'],
                 'direction_names': ['South', 'North'],
                 'fare_class': 'Rapid Transit',
                 'long_name': 'Red Line',
                 'short_name': '',
                 'sort_order': 10010,
                 'text_color': 'FFFFFF',
                 'type': 1},
      'id': 'Red',
      'links': {'self': '/routes/Red'},
      'relationships': {'line': {'data': {'id': 'line-Red', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': 'DA291C',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Mattapan', 'Ashmont'],
                     'direction_names': ['Outbound', 'Inbound'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Mattapan Trolley',
                     'short_name': '',
                     'sort_order': 10011,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Mattapan',
      'links': {'self': '/routes/Mattapan'},
      'relationships': {'line': {'data': {'id': 'line-Mattapan', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': 'ED8B00',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Forest Hills', 'Oak Grove'],
                     'direction_names': ['South', 'North'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Orange Line',
                     'short_name': '',
                     'sort_order': 10020,
                     'text_color': 'FFFFFF',
                     'type': 1},
      'id': 'Orange',
      'links': {'self': '/routes/Orange'},
      'relationships': {'line': {'data': {'id': 'line-Orange', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '00843D',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Boston College',
                                                'Government Center'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Green Line B',
                     'short_name': 'B',
                     'sort_order': 10032,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Green-B',
      'links': {'self': '/routes/Green-B'},
      'relationships': {'line': {'data': {'id': 'line-Green', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '00843D',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Cleveland Circle',
                                                'Government Center'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Green Line C',
                     'short_name': 'C',
                     'sort_order': 10033,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Green-C',
      'links': {'self': '/routes/Green-C'},
      'relationships': {'line': {'data': {'id': 'line-Green', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '00843D',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Riverside', 'Union Square'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Green Line D',
                     'short_name': 'D',
                     'sort_order': 10034,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Green-D',
      'links': {'self': '/routes/Green-D'},
      'relationships': {'line': {'data': {'id': 'line-Green', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '00843D',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Heath Street', 'Lechmere'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Green Line E',
                     'short_name': 'E',
                     'sort_order': 10035,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Green-E',
      'links': {'self': '/routes/Green-E'},
      'relationships': {'line': {'data': {'id': 'line-Green', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '003DA5',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Bowdoin', 'Wonderland'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Blue Line',
                     'short_name': '',
                     'sort_order': 10040,
                     'text_color': 'FFFFFF',
                     'type': 1},
      'id': 'Blue',
      'links': {'self': '/routes/Blue'},
      'relationships': {'line': {'data': {'id': 'line-Blue', 'type': 'line'}}},
      'type': 'route'}]


mock_stop_response_json = {'data': [{'attributes': {'address': 'Dorchester Ave and Ashmont St, Boston, '
                                     'MA 02124',
                          'at_street': None,
                          'description': None,
                          'latitude': 42.28452,
                          'location_type': 1,
                          'longitude': -71.063777,
                          'municipality': 'Boston',
                          'name': 'Ashmont',
                          'on_street': None,
                          'platform_code': None,
                          'platform_name': None,
                          'vehicle_type': None,
                          'wheelchair_boarding': 1},
           'id': 'place-asmnl',
           'links': {'self': '/stops/place-asmnl'},
           'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-asmnl'}},
                             'parent_station': {'data': None},
                             'zone': {'data': None}},
           'type': 'stop'},
          {'attributes': {'address': 'Fellsway St and Milton St, Dorchester, '
                                     'MA 02124',
                          'at_street': None,
                          'description': None,
                          'latitude': 42.279629,
                          'location_type': 1,
                          'longitude': -71.060394,
                          'municipality': 'Boston',
                          'name': 'Cedar Grove',
                          'on_street': None,
                          'platform_code': None,
                          'platform_name': None,
                          'vehicle_type': None,
                          'wheelchair_boarding': 1},
           'id': 'place-cedgr',
           'links': {'self': '/stops/place-cedgr'},
           'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-cedgr'}},
                             'parent_station': {'data': None},
                             'zone': {'data': None}},
           'type': 'stop'},
          {'attributes': {'address': 'Butler St and Branchfield St, '
                                     'Dorchester, MA 02124',
                          'at_street': None,
                          'description': None,
                          'latitude': 42.272429,
                          'location_type': 1,
                          'longitude': -71.062519,
                          'municipality': 'Boston',
                          'name': 'Butler',
                          'on_street': None,
                          'platform_code': None,
                          'platform_name': None,
                          'vehicle_type': None,
                          'wheelchair_boarding': 1},
           'id': 'place-butlr',
           'links': {'self': '/stops/place-butlr'},
           'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-butlr'}},
                             'parent_station': {'data': None},
                             'zone': {'data': None}},
           'type': 'stop'},
          {'attributes': {'address': '1 Adams St, Milton, MA 02186',
                          'at_street': None,
                          'description': None,
                          'latitude': 42.270349,
                          'location_type': 1,
                          'longitude': -71.067266,
                          'municipality': 'Milton',
                          'name': 'Milton',
                          'on_street': None,
                          'platform_code': None,
                          'platform_name': None,
                          'vehicle_type': None,
                          'wheelchair_boarding': 1},
           'id': 'place-miltt',
           'links': {'self': '/stops/place-miltt'},
           'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-miltt'}},
                             'parent_station': {'data': None},
                             'zone': {'data': None}},
           'type': 'stop'},
          {'attributes': {'address': '23 Central Ave, Milton, MA 02186',
                          'at_street': None,
                          'description': None,
                          'latitude': 42.270027,
                          'location_type': 1,
                          'longitude': -71.073444,
                          'municipality': 'Milton',
                          'name': 'Central Avenue',
                          'on_street': None,
                          'platform_code': None,
                          'platform_name': None,
                          'vehicle_type': None,
                          'wheelchair_boarding': 1},
           'id': 'place-cenav',
           'links': {'self': '/stops/place-cenav'},
           'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-cenav'}},
                             'parent_station': {'data': None},
                             'zone': {'data': None}},
           'type': 'stop'},
          {'attributes': {'address': '291 Valley Rd, Milton, MA 02186',
                          'at_street': None,
                          'description': None,
                          'latitude': 42.268347,
                          'location_type': 1,
                          'longitude': -71.081343,
                          'municipality': 'Milton',
                          'name': 'Valley Road',
                          'on_street': None,
                          'platform_code': None,
                          'platform_name': None,
                          'vehicle_type': None,
                          'wheelchair_boarding': 2},
           'id': 'place-valrd',
           'links': {'self': '/stops/place-valrd'},
           'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-valrd'}},
                             'parent_station': {'data': None},
                             'zone': {'data': None}},
           'type': 'stop'},
          {'attributes': {'address': '50 Capen St, Milton, MA 02186',
                          'at_street': None,
                          'description': None,
                          'latitude': 42.267563,
                          'location_type': 1,
                          'longitude': -71.087338,
                          'municipality': 'Milton',
                          'name': 'Capen Street',
                          'on_street': None,
                          'platform_code': None,
                          'platform_name': None,
                          'vehicle_type': None,
                          'wheelchair_boarding': 1},
           'id': 'place-capst',
           'links': {'self': '/stops/place-capst'},
           'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-capst'}},
                             'parent_station': {'data': None},
                             'zone': {'data': None}},
           'type': 'stop'},
          {'attributes': {'address': '500 River St, Boston, MA 02126',
                          'at_street': None,
                          'description': None,
                          'latitude': 42.26762,
                          'location_type': 1,
                          'longitude': -71.092486,
                          'municipality': 'Boston',
                          'name': 'Mattapan',
                          'on_street': None,
                          'platform_code': None,
                          'platform_name': None,
                          'vehicle_type': None,
                          'wheelchair_boarding': 1},
           'id': 'place-matt',
           'links': {'self': '/stops/place-matt'},
           'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-matt'}},
                             'parent_station': {'data': None},
                             'zone': {'data': None}},
           'type': 'stop'}],
 'jsonapi': {'version': '1.0'}}


@patch("get_route.requests.get")
def test_get_subway_data(mocked_get):
    expected = [{'attributes': {'color': 'DA291C',
                 'description': 'Rapid Transit',
                 'direction_destinations': ['Ashmont/Braintree', 'Alewife'],
                 'direction_names': ['South', 'North'],
                 'fare_class': 'Rapid Transit',
                 'long_name': 'Red Line',
                 'short_name': '',
                 'sort_order': 10010,
                 'text_color': 'FFFFFF',
                 'type': 1},
      'id': 'Red',
      'links': {'self': '/routes/Red'},
      'relationships': {'line': {'data': {'id': 'line-Red', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': 'DA291C',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Mattapan', 'Ashmont'],
                     'direction_names': ['Outbound', 'Inbound'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Mattapan Trolley',
                     'short_name': '',
                     'sort_order': 10011,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Mattapan',
      'links': {'self': '/routes/Mattapan'},
      'relationships': {'line': {'data': {'id': 'line-Mattapan', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': 'ED8B00',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Forest Hills', 'Oak Grove'],
                     'direction_names': ['South', 'North'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Orange Line',
                     'short_name': '',
                     'sort_order': 10020,
                     'text_color': 'FFFFFF',
                     'type': 1},
      'id': 'Orange',
      'links': {'self': '/routes/Orange'},
      'relationships': {'line': {'data': {'id': 'line-Orange', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '00843D',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Boston College',
                                                'Government Center'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Green Line B',
                     'short_name': 'B',
                     'sort_order': 10032,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Green-B',
      'links': {'self': '/routes/Green-B'},
      'relationships': {'line': {'data': {'id': 'line-Green', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '00843D',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Cleveland Circle',
                                                'Government Center'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Green Line C',
                     'short_name': 'C',
                     'sort_order': 10033,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Green-C',
      'links': {'self': '/routes/Green-C'},
      'relationships': {'line': {'data': {'id': 'line-Green', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '00843D',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Riverside', 'Union Square'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Green Line D',
                     'short_name': 'D',
                     'sort_order': 10034,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Green-D',
      'links': {'self': '/routes/Green-D'},
      'relationships': {'line': {'data': {'id': 'line-Green', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '00843D',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Heath Street', 'Lechmere'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Green Line E',
                     'short_name': 'E',
                     'sort_order': 10035,
                     'text_color': 'FFFFFF',
                     'type': 0},
      'id': 'Green-E',
      'links': {'self': '/routes/Green-E'},
      'relationships': {'line': {'data': {'id': 'line-Green', 'type': 'line'}}},
      'type': 'route'},
     {'attributes': {'color': '003DA5',
                     'description': 'Rapid Transit',
                     'direction_destinations': ['Bowdoin', 'Wonderland'],
                     'direction_names': ['West', 'East'],
                     'fare_class': 'Rapid Transit',
                     'long_name': 'Blue Line',
                     'short_name': '',
                     'sort_order': 10040,
                     'text_color': 'FFFFFF',
                     'type': 1},
      'id': 'Blue',
      'links': {'self': '/routes/Blue'},
      'relationships': {'line': {'data': {'id': 'line-Blue', 'type': 'line'}}},
      'type': 'route'}]
    mocked_get.return_value.json.return_value = mock_route_response_json
    assert get_route.get_subway_data() == expected


@patch("get_route.get_subway_data")
def test_get_subway_route_long_name(mocked_function):
    expected = {
        'Mattapan Trolley', 'Orange Line', 'Red Line',
        'Green Line C', 'Green Line E', 'Green Line B', 'Green Line D', 'Blue Line'
    }
    mocked_function.return_value = mock_subway_data
    get_subway_data = mocked_function
    assert get_route.get_subway_route_long_name() == expected


@patch("get_route.requests")
def test_get_subway_route_id(mocked_get):
    expected = {
        ('Blue Line', 'Blue'),
        ('Green Line B', 'Green-B'),
        ('Green Line C', 'Green-C'),
        ('Green Line D', 'Green-D'),
        ('Green Line E', 'Green-E'),
        ('Mattapan Trolley', 'Mattapan'),
        ('Orange Line', 'Orange'),
        ('Red Line', 'Red')
    }
    mocked_get.return_value = Mock(
        status_code=200,
        json=mock_stop_response_json
    )
    assert get_route.get_subway_route_id() == expected


@patch("requests.get")
def test_get_subway_route_stops(mocked_get):
    expected = [{'attributes': {'address': 'Dorchester Ave and Ashmont St, Boston, MA 02124',
                 'at_street': None,
                 'description': None,
                 'latitude': 42.28452,
                 'location_type': 1,
                 'longitude': -71.063777,
                 'municipality': 'Boston',
                 'name': 'Ashmont',
                 'on_street': None,
                 'platform_code': None,
                 'platform_name': None,
                 'vehicle_type': None,
                 'wheelchair_boarding': 1},
  'id': 'place-asmnl',
  'links': {'self': '/stops/place-asmnl'},
  'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-asmnl'}},
                    'parent_station': {'data': None},
                    'zone': {'data': None}},
  'type': 'stop'},
 {'attributes': {'address': 'Fellsway St and Milton St, Dorchester, MA 02124',
                 'at_street': None,
                 'description': None,
                 'latitude': 42.279629,
                 'location_type': 1,
                 'longitude': -71.060394,
                 'municipality': 'Boston',
                 'name': 'Cedar Grove',
                 'on_street': None,
                 'platform_code': None,
                 'platform_name': None,
                 'vehicle_type': None,
                 'wheelchair_boarding': 1},
  'id': 'place-cedgr',
  'links': {'self': '/stops/place-cedgr'},
  'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-cedgr'}},
                    'parent_station': {'data': None},
                    'zone': {'data': None}},
  'type': 'stop'},
 {'attributes': {'address': 'Butler St and Branchfield St, Dorchester, MA '
                            '02124',
                 'at_street': None,
                 'description': None,
                 'latitude': 42.272429,
                 'location_type': 1,
                 'longitude': -71.062519,
                 'municipality': 'Boston',
                 'name': 'Butler',
                 'on_street': None,
                 'platform_code': None,
                 'platform_name': None,
                 'vehicle_type': None,
                 'wheelchair_boarding': 1},
  'id': 'place-butlr',
  'links': {'self': '/stops/place-butlr'},
  'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-butlr'}},
                    'parent_station': {'data': None},
                    'zone': {'data': None}},
  'type': 'stop'},
 {'attributes': {'address': '1 Adams St, Milton, MA 02186',
                 'at_street': None,
                 'description': None,
                 'latitude': 42.270349,
                 'location_type': 1,
                 'longitude': -71.067266,
                 'municipality': 'Milton',
                 'name': 'Milton',
                 'on_street': None,
                 'platform_code': None,
                 'platform_name': None,
                 'vehicle_type': None,
                 'wheelchair_boarding': 1},
  'id': 'place-miltt',
  'links': {'self': '/stops/place-miltt'},
  'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-miltt'}},
                    'parent_station': {'data': None},
                    'zone': {'data': None}},
  'type': 'stop'},
 {'attributes': {'address': '23 Central Ave, Milton, MA 02186',
                 'at_street': None,
                 'description': None,
                 'latitude': 42.270027,
                 'location_type': 1,
                 'longitude': -71.073444,
                 'municipality': 'Milton',
                 'name': 'Central Avenue',
                 'on_street': None,
                 'platform_code': None,
                 'platform_name': None,
                 'vehicle_type': None,
                 'wheelchair_boarding': 1},
  'id': 'place-cenav',
  'links': {'self': '/stops/place-cenav'},
  'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-cenav'}},
                    'parent_station': {'data': None},
                    'zone': {'data': None}},
  'type': 'stop'},
 {'attributes': {'address': '291 Valley Rd, Milton, MA 02186',
                 'at_street': None,
                 'description': None,
                 'latitude': 42.268347,
                 'location_type': 1,
                 'longitude': -71.081343,
                 'municipality': 'Milton',
                 'name': 'Valley Road',
                 'on_street': None,
                 'platform_code': None,
                 'platform_name': None,
                 'vehicle_type': None,
                 'wheelchair_boarding': 2},
  'id': 'place-valrd',
  'links': {'self': '/stops/place-valrd'},
  'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-valrd'}},
                    'parent_station': {'data': None},
                    'zone': {'data': None}},
  'type': 'stop'},
 {'attributes': {'address': '50 Capen St, Milton, MA 02186',
                 'at_street': None,
                 'description': None,
                 'latitude': 42.267563,
                 'location_type': 1,
                 'longitude': -71.087338,
                 'municipality': 'Milton',
                 'name': 'Capen Street',
                 'on_street': None,
                 'platform_code': None,
                 'platform_name': None,
                 'vehicle_type': None,
                 'wheelchair_boarding': 1},
  'id': 'place-capst',
  'links': {'self': '/stops/place-capst'},
  'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-capst'}},
                    'parent_station': {'data': None},
                    'zone': {'data': None}},
  'type': 'stop'},
 {'attributes': {'address': '500 River St, Boston, MA 02126',
                 'at_street': None,
                 'description': None,
                 'latitude': 42.26762,
                 'location_type': 1,
                 'longitude': -71.092486,
                 'municipality': 'Boston',
                 'name': 'Mattapan',
                 'on_street': None,
                 'platform_code': None,
                 'platform_name': None,
                 'vehicle_type': None,
                 'wheelchair_boarding': 1},
  'id': 'place-matt',
  'links': {'self': '/stops/place-matt'},
  'relationships': {'facilities': {'links': {'related': '/facilities/?filter[stop]=place-matt'}},
                    'parent_station': {'data': None},
                    'zone': {'data': None}},
  'type': 'stop'}]
    mocked_get.return_value = Mock(
        status_code=200,
        json=mock_stop_response_json
    )
    assert get_route.get_subway_route_stops("Mattapan") == expected


def get_subway_route_stops_side_effect_function(route_id):
    mapping = {
        'Red': [item for item in range(22)],
        'Blue': [item for item in range(12)],
        'Green-D': [item for item in range(25)],
        'Green-E': [item for item in range(20)],
        'Green-B': [item for item in range(23)],
        'Green-C': [item for item in range(20)],
        'Mattapan': [item for item in range(8)],
        'Orange': [item for item in range(20)],
    }
    return mapping[route_id]


def test_list_subway_route_stops():
    expected_max = "Subway route with most stops: (25, 'Green Line D')"
    expected_min = "Subway route with least stops: (8, 'Mattapan Trolley')"
    with patch(
            "get_route.get_subway_route_stops",
            side_effect=get_subway_route_stops_side_effect_function
    ) as route_stop_mock, patch(
        "get_route.get_subway_route_id"
    ) as route_id_mock:
        route_id_mock.return_value = {
            ('Blue Line', 'Blue'),
            ('Green Line B', 'Green-B'),
            ('Green Line C', 'Green-C'),
            ('Green Line D', 'Green-D'),
            ('Green Line E', 'Green-E'),
            ('Mattapan Trolley', 'Mattapan'),
            ('Orange Line', 'Orange'),
            ('Red Line', 'Red'),
        }
        assert get_route.list_subway_route_stops(show_max=True) == expected_max
        assert get_route.list_subway_route_stops(show_max=False) == expected_min
